### ISSUE TITLE
Unable to run the examples provided

### ISSUE THREAD

**Issue by chesschi** [deepsense-ai/tensorflow_on_slurm#2]
After cloning the repo, I have run download_data.sh and try to run the example script. When I try to run examples/cifar-10/main.py, it showed the following error:

```
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    data_elem = pickle.load(fo)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)
```

Please can you suggest how can I fix the error?

Many thanks!

**Comment by tgrel** [comment]
I haven't encountered this error. Are you using python2 or python3? Can you provide more information about your environment?

**Comment by chesschi** [comment]
I am using python3 and run this in Ubuntu 17.10.

**Comment by chesschi** [comment]
Sorry something wrong with my mouse to re-open/close the issue.

**Comment by chesschi** [comment]
Just tested on python 2 and it is working

**Comment by ianferreira** [comment]
data_elem = pickle.load(fo, encoding='latin1') for python 3
